### ISSUE TITLE
Fix AttributeError

### ISSUE THREAD

**Issue by GoodGuyGroves** [GoodGuyGroves/CSGO-Pickup#10]
I've seen this error a few times, I think it raises only SOMETIMES on nick changes or quits? Not entirely sure but I should probably try fix it some time.

```
2015-03-29 22:28:44+0200 [-] Unhandled error in Deferred:
2015-03-29 22:28:44+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
            self.runUntilCurrent()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 773, in runUntilCurrent
            f(*a, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 368, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/russ/ibid_pickup/ibid/source/irc.py", line 191, in respond
            self.send(response)
          File "/home/russ/ibid_pickup/ibid/source/irc.py", line 198, in send
            target = response['target'].split('!')[0]
        exceptions.AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by zoidyzoidzoid** [comment]
None of your own code in there. That's shitty to debug. :?

**Comment by GoodGuyGroves** [comment]
This might actually give more info, two quits and two slightly different traces:

DEBUG core.dispatcher: Received event from shadowfire source
ERROR core.dispatcher: Exception occured in Format processor of core plugin.
Event: {'account': None, 'responses': [{'reply': u'TeamA[2/5]: (Hopper), (?), (?), (?), (hypeR) TeamB[5/5]: (Shushi), (UnholyCurse), (Lenn), (Ibot23), (snipe_jones)', 'address': False, 'target': None, 'conflate': True, 'source': u'shadowfire'}], 'source': u'shadowfire', 'state': u'offline', 'processed': True, 'time': datetime.datetime(2015, 3, 29, 20, 31, 4, 751852), 'identity': 384, 'message': u'Quit: http://www.mibbit.com ajax IRC Client', 'type': u'state', 'public': True, 'channel': None, 'sender': {'nick': u'Apathy', 'connection': u'Apathy', 'id': u'Apathy'}}
Traceback (most recent call last):
  File "/home/russ/ibid_pickup/ibid/core.py", line 29, in process
    processor.process(event)
  File "/home/russ/ibid_pickup/ibid/plugins/core.py", line 204, in process
    maxlen = ibid.sources[source].truncation_point(response, event)
  File "/home/russ/ibid_pickup/ibid/source/irc.py", line 382, in truncation_point
    target = response['target'].split('!')[0]
AttributeError: 'NoneType' object has no attribute 'split'
DEBUG core.dispatcher: {'account': None, 'responses': [{'reply': u'TeamA[2/5]: (Hopper), (?), (?), (?), (hypeR) TeamB[5/5]: (Shushi), (UnholyCurse), (Lenn), (Ibot23), (snipe_jones)', 'address': False, 'target': None, 'conflate': True, 'source': u'shadowfire'}], 'complain': u'exception', 'source': u'shadowfire', 'state': u'offline', 'processed': True, 'time': datetime.datetime(2015, 3, 29, 20, 31, 4, 751852), 'identity': 384, 'exc_info': (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'split'",), <traceback object at 0x3cd3950>), 'message': u'Quit: http://www.mibbit.com ajax IRC Client', 'type': u'state', 'public': True, 'channel': None, 'sender': {'nick': u'Apathy', 'connection': u'Apathy', 'id': u'Apathy'}}
DEBUG core.dispatcher: Returning event to shadowfire source
2015-03-29 22:31:04+0200 [-] Unhandled error in Deferred:
2015-03-29 22:31:04+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in mainLoop
            self.runUntilCurrent()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 773, in runUntilCurrent
            f(_a, *_kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 368, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "/home/russ/ibid_pickup/ibid/source/irc.py", line 191, in respond
            self.send(response)
          File "/home/russ/ibid_pickup/ibid/source/irc.py", line 198, in send
            target = response['target'].split('!')[0]
        exceptions.AttributeError: 'NoneType' object has no attribute 'split'
